name: ci
on: [pull_request, push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run eslint

  test:
    runs-on: ubuntu-latest
    services:
      php:
        image: jieter/minimal-php
        options: "-v /${{ github.workspace }}:/home/php/ --name php"
        ports:
          - 8000:8000 # dst:src

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      # The container is started before the checkout action runs, so we should restart
      # the container to make it have access to the workspace
      # (https://github.community/t/services-and-volumes/16313).
      - name: restart php container
        uses: docker://docker
        with:
          args: docker restart php
      - run: npm run spec
        env:
          BASE_URL: http://localhost:8000/public/
