name: deploy
on: workflow_dispatch

jobs:
  deploy:
    needs: [tests]
    runs-on: ubuntu-latest
    name: Deploy 'master' to sailplanner.nl
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.SAILPLANNER_DEPLOY_KEY }}
      - run: npm install
      - run: npm run publish
